version: "3"
services:
  postgresql:
    build: ./postgresql/
    container_name: "docker-postgresql-work"
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d # 初期データ投入
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    hostname: postgresql
    restart: always
    ports:
      - 5432:5432

